name: Github actions docker example

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Run a plain docker debian bash command
      run: docker run debian:latest bash -c "echo it works\!"
    - uses: actions/checkout@v2
    - name: Build the docker image
      run: docker build -t github-actions-docker-example .
    - name: Run the built docker image
      run: docker run -it github-actions-docker-example:latest bash -c "echo it works\!"
      
