name: Github actions docker example

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the docker image
      run: docker build -t github-actions-docker-example .
    - name: Run the built docker image
      run: docker run -i github-actions-docker-example --name github-actions-docker-example
